[package]
name = "upgrade"
version = "0.2.2"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A helpful library for upgradeing the self program. Welcome to submit PR."
readme = "README.md"
license = "GPL-3.0"
repository = "https://github.com/xuxiaocheng0201/upgrade/"
keywords = ["upgrade", "self", "program"]

[dependencies]
anyhow = "^1.0"
encoding_rs = "~0.8"
windows = { version = "~0.52", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_System_Diagnostics_Debug", "Win32_System_Kernel", "Win32_System_Memory"] }

[build-dependencies]
anyhow = "^1.0"
