[package]
name = "upgrade"
version = "0.2.0"
authors = ["xuxiaocheng <2762267080@qq.com>"]
edition = "2021"
description = "A helpful library for upgradeing the self program. Welcome to submit PR."
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/xuxiaocheng0201/upgrade/"

[dependencies]
anyhow = "^1.0"
encoding_rs = "~0.8"

[dependencies.windows]
version = "~0.52"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_Memory"
]
